/**
 * Generated by orval v8.12.2 🍺
 * Do not edit manually.
 * RestaurantOS API
 * OpenAPI spec version: 1.0.0
 */
export type GetMenuItems200Item = {
  id: number;
  /** @nullable */
  categoryId: number | null;
  name: string;
  price: string;
  /** @nullable */
  available: boolean | null;
};

export type getMenuItemsResponse200 = {
  data: GetMenuItems200Item[]
  status: 200
}

export type getMenuItemsResponseSuccess = (getMenuItemsResponse200) & {
  headers: Headers;
};
;

export type getMenuItemsResponse = (getMenuItemsResponseSuccess)

export const getGetMenuItemsUrl = () => {




  return `/menu-items`
}

export const getMenuItems = async ( options?: RequestInit): Promise<getMenuItemsResponse> => {

  const res = await fetch(getGetMenuItemsUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMenuItemsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMenuItemsResponse
}
